#@ load("@ytt:data", "data")

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tap-certificate
  namespace: tap-install
spec:
  secretName: tap-tls-secret
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-contour-cluster-issuer
  dnsNames:
  - #@ data.values.tap.cert.cn
