---
catalog: https://github.com/tanzu-end-to-end/acme-catalog/blob/main/catalog-info.yaml
git:
  url: https://github.com/tanzu-end-to-end/tap-gitops-reference
  ref: origin/h2o
paths:
  - clusters/common/config
  - clusters/appref-1/config
tap:
  registry:
    host: registry.gcp.ellin.net
    location: tap/tbs
  supplychainregistry:
    host: registry.gcp.ellin.net
    location: tap/sc
  base:
    domain: ref.appref.end2end.link
