apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: tap-bug-bash-iterate
  region: us-east-2



nodeGroups:
  - name: ng-1
    instanceType: c5.2xlarge
    desiredCapacity: 4
    amiFamily: AmazonLinux2
    containerRuntime: containerd
    availabilityZones: ['us-east-2a']
availabilityZones: ['us-east-2a', 'us-east-2b']
