apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: hello
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: hello
    apps.tanzu.vmware.com/has-tests: "true"
  namespace: canary
spec:
  build:
    env:
    - name: BP_JVM_VERSION
      value: '17'
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
    - name: gitops_repository_name
      value: "trp-gitops-canary"
  source:
    git:
      url: https://github.com/tanzu-end-to-end/trp-tanzu-java-web-app.git
      ref:
        branch: main
