#@ load("@ytt:data", "data")

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: learningcenter-cert
  namespace: tap-install
spec:
  secretName: learningcenter-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: vault-cluster-issuer
  dnsNames:
  - #@ "*." + data.values.tap.domains.learningcenter
---
#! Install here vs app-contents/certs because we want to make sure the 
#! learning center namespace has been created.
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: learningcenter-cert-tls
  namespace: tap-install
spec:
  toNamespaces:
  - 'learningcenter'
