apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline
  labels:
    apps.tanzu.vmware.com/pipeline: test     # (!) required
spec:
  params:
    - name: source-url                        # (!) required
    - name: source-revision                   # (!) required
  tasks:
    - name: test
      params:
        - name: source-url
          value: $(params.source-url)
        - name: source-revision
          value: $(params.source-revision)
      taskSpec:
        params:
          - name: source-url
          - name: source-revision
        steps:
          - name: test
            image: registry.gcp.ellin.net/library/gradle
            script: |-
              cd `mktemp -d`
              # Added -m due to issue with rosource plugin complaining about
              # missing messages_es.properties.
              # https://vmware.slack.com/archives/C0186SB6ATY/p1644235576354359
              wget -qO- $(params.source-url) | tar xvz -m
              pwd
              MVNW=mvnw
              GRADLE="build.gradle"
              if [ -f "$MVNW" ]; then
                  ./mvnw test
              elif [ -f "$GRADLE" ]; then
                  gradle test --debug
              else 
                  echo "ERROR: No supported test framework."
                  echo "no error right now this is probably a dotnet wl"
                  #exit 1
              fi