#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
  namespace: dotnet-todos
spec:
  replicas: 1
  selector:
     matchLabels:
       app: mssql
  serviceName: mssql
  template:
    metadata:
      labels:
        app: mssql
        app-tier: db
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        fsGroup: 10001
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: RandomPassword!23
        volumeMounts:
        - name: mssql
          mountPath: /var/opt/mssql
        resources:
          requests:
            memory: 1G
            cpu: "1"
          limits:
            memory: 2G
            cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: mssql
        annotations:
          kapp.k14s.io/owned-for-deletion: ""
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
  namespace: dotnet-todos
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP