#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")
---
#@ def config():
profile: full
ceip_policy_disclosed: true #! Installation fails if this is set to 'false'
appliveview_connector:
  backend:
    host: #@ data.values.tap.appliveview_connector
cnrs:
  domain_name: #@ data.values.tap.domains.base
  ingress:
    internal:
      namespace: tanzu-system-ingress
    external:
      namespace: tanzu-system-ingress
buildservice:
  kp_default_repository: #@ "{}/{}".format(data.values.tap.credentials.registry.host, data.values.tap.credentials.registry.repositories.buildService)
  kp_default_repository_username: #@ data.values.tap.credentials.registry.username
  kp_default_repository_password: #@ data.values.tap.credentials.registry.password
supply_chain: basic
shared:
  ingress_domain: #@ data.values.tap.domains.base
learningcenter:
  ingressSecret: 
    secretName:  learningcenter-cert-tls
tap_gui:
  service_type: ClusterIP
  tls:
    namespace: tap-install
    secretName: tap-tls-secret
  app_config:
    integrations:
      github:
        - host: github.com
          token: #@ data.values.git_pr.password
    auth:
      allowGuestAccess: true
      environment: development
      providers:
        okta:
          development:
            clientId: #@ data.values.appsso.clientId
            clientSecret: #@ data.values.appsso.clientSecret
            audience: #@ data.values.appsso.audience
    techdocs:
      builder: 'external'
      publisher:
        type: 'awsS3'
        awsS3:
          bucketName: #@ data.values.aws.s3.bucket
          credentials:
            accessKeyId: #@ data.values.aws.s3.access_key
            secretAccessKey: #@ data.values.aws.s3.secret_key
          region: #@ data.values.aws.s3.region
          s3ForcePathStyle: false
    supplyChain:
      enablePlugin: true
    proxy:
      /metadata-store:
        target: https://metadata-store-app.metadata-store.svc.cluster.local:8443/api/v1
        changeOrigin: true
        secure: true
        ca: #@ base64.decode(data.values.tap.metadatastore.ca)
        headers:
          Authorization: #@ "Bearer " + data.values.tap.metadatastore.auth_token
          X-Custom-Source: project-star
    app:
        baseUrl: #@ "https://{}".format(data.values.tap.domains.tapGui)
    catalog:
        locations:
        - type: url
          target: #@ data.values.tap.catalog
    backend:
        baseUrl: #@ "https://{}".format(data.values.tap.domains.tapGui)
        cors:
            origin: #@ "https://{}".format(data.values.tap.domains.tapGui)
grype:
  targetImagePullSecret: registry-credentials
  targetSourceSshSecret: git-ssh
  namespace: tap-install
  metadataStore:
    url: #@ data.values.tap.domains.metadata_store
    caSecret:
      name: store-ca-cert
      importFromNamespace: metadata-store-secrets
    authSecret:
      name: store-auth-token
      importFromNamespace: metadata-store-secrets
ootb_supply_chain_basic:
  registry:
    server: #@ data.values.tap.credentials.supplychainregistry.host
    repository: #@ data.values.tap.credentials.supplychainregistry.repositories.ootbSupplyChain
  gitops:
    commit_strategy: pull_request
    branch: test
    server_address: #@ data.values.tap.supply_chain.gitops.server_address
    repository_owner: #@ data.values.tap.supply_chain.gitops.repository_owner
    ssh_secret: git-https
    pull_request:
      commit_branch: supply-chain
      server_kind: github
      pull_request_title: Ready for review
      pull_request_body: Pull Request by TAP

appliveview:
  tls:
    namespace: tap-install
    #! Not consistent with others
    secretName: tap-tls-secret
scanning:
  metadataStore:
    url: ""
metadata_store:
  app_service_type: ClusterIP
accelerator:
  ingress:
    enable_tls: true
    include: true #! This should be able to be removed since I have shared.ingress_domain set above.  All others work, but for accelerator I had to explicitly set this
  tls:
    namespace: tap-install
    secret_name: tap-tls-secret
excluded_packages:
- cert-manager.tanzu.vmware.com
- contour.tanzu.vmware.com
- image-policy-webhook.signing.apps.tanzu.vmware.com
- policy.apps.tanzu.vmware.com

package_overlays:
- name:  tap-gui
  secrets:
  - name: cluster-viewer-config-overlay
- name:  learningcenter
  secrets:
  - name: learningcenterconfig-overlay
- name: "ootb-templates"
  secrets:
  - name: ootb-templates-overlay
- name:  cnrs
  secrets:
  - name: cnrs-network-config-overlay
  - name: cnrs-certmanager-config-overlay
#@ end
---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule: "delete after deleting tap"

type: Opaque
stringData:
  values.yml: #@ yaml.encode(config())
